services:
  mariadb:
    build: .
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom-network:
        ipv4_address: 192.168.100.210  # Static IP for the MariaDB container

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"  # Exposing port 80 inside the container to port 8080 on the host
    volumes:
      - ./html:/usr/share/nginx/html  # Bind local 'html' directory to NGINX's document root
      - ./nginx.conf:/etc/nginx/nginx.conf  # Optional: custom NGINX config
    networks:
      custom-network:
        ipv4_address: 192.168.100.200  # Static IP for the NGINX container

volumes:
  db_data:

networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  # Custom subnet for the network

