# Use the official MariaDB image from Docker Hub
FROM mariadb:latest

# Set environment variables for the MariaDB root user
ENV MARIADB_ROOT_PASSWORD=password
ENV MARIADB_DATABASE=warehouse

# Expose the default MariaDB port
EXPOSE 3306

